---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "wsgi-sample-app"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "wsgi-chunked-req"
    spec:
      containers:
        - name: nginx
          image: "nginx:1.11-alpine"
          command: ["/bin/sh","-c"]
          args: ["cp /var/run/pod_shared/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
          volumeMounts:
            - name: shared-dir
              mountPath: /var/run/pod_shared
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
        - name: sample-app
          image: "rafaelcaricio/uwsgi_sample_app:0.1.1"
          env:
            - name: APP_LOG_LEVEL
              value: "DEBUG"
          command: ["/bin/bash","-c"]
          args: ["cp /configs/nginx.conf /var/run/pod_shared; uwsgi --yaml uwsgi.yaml"]
          readinessProbe:
            exec:
              command:
              - stat
              - /var/run/pod_shared/simple_server.sock
            initialDelaySeconds: 1
            periodSeconds: 3
          volumeMounts:
            - name: shared-dir
              mountPath: /var/run/pod_shared
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
      volumes:
        - name: shared-dir
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: wsgi-sample-app
spec:
  type: LoadBalancer
  selector:
    app: "wsgi-chunked-req"
  ports:
    - port: 8080
      name: web
